/**
 * Canonical stats for each unit kind. The server unit classes copy these
 * onto each instance. Keys match the spawn type. Alternates keep their
 * base `type` in play (troop, skirmisher, …) and carry a `variant` id.
 *
 * shotSlowSpeed is how long a received shot slows the unit, in seconds.
 * slowFactor is the walk-speed multiplier while that slow lasts.
 * engageRange is the fraction of range at which the unit opens fire on its own.
 * chargeSpeed is the walk multiplier while charging (1 = no bonus).
 * fatigue is the max fatigue pool (breaks when fatigue % exceeds hp %).
 * chargeMultiplier and flankMultiplier apply to outgoing damage.
 * officerDamageMultiplier scales damage when hitting an officer.
 */

const SHOT = {
  shotSlowSpeed: 0.6,
  slowFactor: 0.4,
  chargeMultiplier: 1.2,
  projectileSize: 4,
  projectileSpeed: 220,
  projectileColor: "#f3d27a",
  meleeReach: 30,
  radius: 10,
  fatigue: 100,
  splashWholeLine: false,
  attackBuff: 0,
  speedBuff: 0,
  buffRange: 0,
};

export const UNIT_STATS = {
  troop: {
    ...SHOT,
    hp: 200,
    rangedDamage: 10,
    meleeDamage: 10,
    range: 200,
    engageRange: 0.5,
    chargeSpeed: 1.5,
    flankMultiplier: 1.2,
    rangedCooldown: 1,
    meleeCooldown: 1,
    speed: 20,
    cost: 120,
    lineBonus: 0.2,
    fightsMelee: true,
    splash: 0,
    avoidMeleeBand: false,
    restoreRange: 0,
    restoreRate: 0,
    officerDamageMultiplier: 1,
  },
  skirmisher: {
    ...SHOT,
    hp: 100,
    rangedDamage: 4,
    meleeDamage: 2,
    range: 200,
    engageRange: 1,
    chargeSpeed: 1.5,
    flankMultiplier: 1.2,
    rangedCooldown: 1,
    meleeCooldown: 1,
    speed: 20,
    cost: 120,
    lineBonus: 0,
    fightsMelee: true,
    splash: 0,
    avoidMeleeBand: false,
    restoreRange: 0,
    restoreRate: 0,
    officerDamageMultiplier: 2,
  },
  dragoon: {
    ...SHOT,
    hp: 200,
    rangedDamage: 5,
    meleeDamage: 20,
    range: 200,
    engageRange: 0.5,
    chargeSpeed: 1.5,
    flankMultiplier: 1.8,
    rangedCooldown: 1,
    meleeCooldown: 1,
    speed: 40,
    cost: 240,
    lineBonus: 0,
    fightsMelee: true,
    splash: 0,
    avoidMeleeBand: false,
    restoreRange: 0,
    restoreRate: 0,
    officerDamageMultiplier: 1,
  },
  cannon: {
    ...SHOT,
    hp: 200,
    rangedDamage: 90,
    meleeDamage: 0,
    range: 500,
    engageRange: 0.5,
    chargeSpeed: 1,
    flankMultiplier: 1.2,
    rangedCooldown: 4,
    meleeCooldown: 4,
    speed: 20,
    cost: 360,
    lineBonus: 0,
    fightsMelee: false,
    splash: 0.5,
    avoidMeleeBand: true,
    restoreRange: 0,
    restoreRate: 0,
    officerDamageMultiplier: 1,
  },
  officer: {
    ...SHOT,
    hp: 50,
    rangedDamage: 5,
    meleeDamage: 5,
    range: 100,
    engageRange: 0.5,
    chargeSpeed: 1.5,
    flankMultiplier: 1.2,
    rangedCooldown: 1,
    meleeCooldown: 1,
    speed: 20,
    cost: 180,
    lineBonus: 0,
    fightsMelee: true,
    splash: 0,
    avoidMeleeBand: false,
    restoreRange: 100,
    restoreRate: 1,
    officerDamageMultiplier: 1,
  },

  // Alternates (same base type in play; white square behind the icon)

  /** Troop with more hit points and shorter musket range. */
  grenadier: {
    ...SHOT,
    hp: 280,
    rangedDamage: 10,
    meleeDamage: 10,
    range: 150,
    engageRange: 0.5,
    chargeSpeed: 1.5,
    flankMultiplier: 1.2,
    rangedCooldown: 1,
    meleeCooldown: 1,
    speed: 20,
    cost: 120,
    lineBonus: 0.2,
    fightsMelee: true,
    splash: 0,
    avoidMeleeBand: false,
    restoreRange: 0,
    restoreRate: 0,
    officerDamageMultiplier: 1,
  },
  /** Skirmisher: longer shot, harder hit, slower reload. */
  rifle: {
    ...SHOT,
    hp: 100,
    rangedDamage: 20,
    meleeDamage: 2,
    range: 300,
    engageRange: 1,
    chargeSpeed: 1.5,
    flankMultiplier: 1.2,
    rangedCooldown: 2,
    meleeCooldown: 1,
    speed: 20,
    cost: 120,
    lineBonus: 0,
    fightsMelee: true,
    splash: 0,
    avoidMeleeBand: false,
    restoreRange: 0,
    restoreRate: 0,
    officerDamageMultiplier: 2,
  },
  /** Dragoon: normal flank multiplier, stronger charge hits. */
  lancer: {
    ...SHOT,
    hp: 200,
    rangedDamage: 5,
    meleeDamage: 20,
    range: 200,
    engageRange: 0.5,
    chargeSpeed: 1.5,
    flankMultiplier: 1.2,
    chargeMultiplier: 1.5,
    rangedCooldown: 1,
    meleeCooldown: 1,
    speed: 40,
    cost: 240,
    lineBonus: 0,
    fightsMelee: true,
    splash: 0,
    avoidMeleeBand: false,
    restoreRange: 0,
    restoreRate: 0,
    officerDamageMultiplier: 1,
  },
  /** Cannon: shorter reach, half shell damage, full damage to the whole line. */
  howitzer: {
    ...SHOT,
    hp: 200,
    rangedDamage: 45,
    meleeDamage: 0,
    range: 350,
    engageRange: 0.5,
    chargeSpeed: 1,
    flankMultiplier: 1.2,
    rangedCooldown: 4,
    meleeCooldown: 4,
    speed: 20,
    cost: 360,
    lineBonus: 0,
    fightsMelee: false,
    splash: 1,
    splashWholeLine: true,
    avoidMeleeBand: true,
    restoreRange: 0,
    restoreRate: 0,
    officerDamageMultiplier: 1,
  },
  /** Officer that also raises nearby attack and walk speed. */
  colorGuard: {
    ...SHOT,
    hp: 50,
    rangedDamage: 5,
    meleeDamage: 5,
    range: 100,
    engageRange: 0.5,
    chargeSpeed: 1.5,
    flankMultiplier: 1.2,
    rangedCooldown: 1,
    meleeCooldown: 1,
    speed: 20,
    cost: 180,
    lineBonus: 0,
    fightsMelee: true,
    splash: 0,
    avoidMeleeBand: false,
    restoreRange: 100,
    restoreRate: 1,
    officerDamageMultiplier: 1,
    buffRange: 100,
    attackBuff: 0.15,
    speedBuff: 0.15,
  },
};

export function unitStats(type) {
  return UNIT_STATS[type] || UNIT_STATS.troop;
}

/** Base buy type → unlocked alternate spawn key. */
export const UNIT_VARIANTS = {
  troop: "grenadier",
  skirmisher: "rifle",
  dragoon: "lancer",
  cannon: "howitzer",
  officer: "colorGuard",
};

/** Short labels for buy buttons and inspect text. */
export const UNIT_LABELS = {
  troop: "Troop",
  skirmisher: "Skirmish",
  dragoon: "Dragoon",
  cannon: "Cannon",
  officer: "Officer",
  grenadier: "Grenadier",
  rifle: "Rifle",
  lancer: "Lancer",
  howitzer: "Howitzer",
  colorGuard: "Color",
};

/** Lane-buy catalog drawn on the canvas (base units only). */
export const BUY_UNITS = [
  { type: "troop", label: "Troop", fill: "#2a4158", stroke: "#3d5a7a" },
  { type: "skirmisher", label: "Skirmish", fill: "#243a32", stroke: "#3a6a5a" },
  { type: "dragoon", label: "Dragoon", fill: "#322848", stroke: "#5a4a7a" },
  { type: "cannon", label: "Cannon", fill: "#3a3428", stroke: "#6a5a3a" },
  { type: "officer", label: "Officer", fill: "#3a2a28", stroke: "#7a4a3a" },
];
